version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}
  django_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/app
      - django_media:/app/gfbio_submissions/media
      # git has to be initialized, remote origin has to be set.
      - /home/maweber/devel/git-python-test:/gfbio-submission-auditing-tests
    environment:
      - POSTGRES_USER=gfbio_submissions
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    environment:
      - POSTGRES_USER=gfbio_submissions


  redis:
    image: redis:3.0

  celeryworker:
    # https://github.com/docker/compose/issues/3220
    <<: *django
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker.sh

  celerybeat:
    # https://github.com/docker/compose/issues/3220
    <<: *django
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat.sh

